name: Build Flet App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK (Flet Action)
        uses: flet-dev/flet-build-action@v1
        with:
          project-path: '.'
          python-version: '3.10'
          package-name: 'com.pazany.music'
          product-name: 'AntiYandex'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AntiYandex-APK
          path: build/apk/*.apk
